apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-increse-deployment 
  labels:
    app: nginx               # Add a label for better identification
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: replica-increse
  template:
    metadata:
      labels:
        app: replica-increse
    spec:
      containers:
      - name: replica-increse
        image: manasitdk/ubuntu_images:ubuntu-apache24.04
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: replica-increse-service
spec:
  type: NodePort
  selector:
    app: replica-increse
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30101    # NodePort range: 30000-32767
